module.exports = {
  USER_STATUS: {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
    SUSPENDED: "SUSPENDED",
  },
  ORGANIZATION_STATUS: {
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED",
  },
  RESOURCE_STATUS: {
    DRAFT: "DRAFT",
    PUBLISHED: "PUBLISHED",
    ARCHIVED: "ARCHIVED",
  },
  PERMISSIONS: {
    // ORGANIZATION ADMIN 
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",
    DEACTIVATE_USER: "DEACTIVATE_USER",

    // ORGANIZATION ADMIN
    CREATE_ROLE: "CREATE_ROLE",
    ASSIGN_ROLE: "ASSIGN_ROLE",

    // ORGANIZATION MANAGER
    CREATE_RESOURCE: "CREATE_RESOURCE",
    UPDATE_RESOURCE: "UPDATE_RESOURCE",
    // ORGANIZATION EMPLOYEE, MANAGER, ADMIN
    VIEW_RESOURCE: "VIEW_RESOURCE",
    // ORGANIZATION ADMIN
    DELETE_RESOURCE: "DELETE_RESOURCE",
  },
};
